title: Docker Scripts to run in PowerShell
description: >-
  Docker scripts to run in PowerShell

baseurl: ""
url: "https://docker-powershell.vercel.app"

email: hebertcisco@outlook.com
twitter_username: hebertcisco
github_username:  hebertcisco
# Build settings

theme: minima

plugins:
  - jekyll-feed

safe: true
#engine: ''

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
